name: assignment-test

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  unit-test:
    container: cuaesd/aesd-autotest:24-unit-test
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Use the latest version
        with:
          submodules: recursive  # Ensures that submodules are initialized and updated
      - name: Run unit test
        run: ./unit-test.sh

  full-test:
    container: cuaesd/aesd-autotest:24-assignment5
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Use the latest version
        with:
          submodules: recursive  # Ensures that submodules are initialized and updated
      - name: Run full test
        run: ./full-test.sh
